name: Issue:Bug
description: Report a bug or problem in sqeleton
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of what bug is.
    validations:
      required: True 

  - type: dropdown
    id: type
    attributes:
      label: feature type
      description: report?
      multiple: True
      options:
        - report
        - fix

  - type: markdown
    attributes:
      value: Explain how to reproduce the bug or problem
  
  - type: textarea
    id: code
    attributes:
      label: code
      description: Paste code here.
      render: python
    validations:
      required: False
  
  - type: textarea
    id: log
    attributes:
      label: log
      description: Paste long log.
      render: shell
    validations:
      required: False

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: describe expected behavior.
    validations:
      required: False
  
  - type: textarea
    id: todo
    attributes:
      label: To Do
      description: describe to do.
    validations:
      required: False
