name: Issue:Feature
description: New feature or change in sqeleton
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of the feature.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Purpose
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Describe how this feature would be used.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"

  - type: textarea
    id: alternative
    attributes:
      label: Alternatives considered
      description: Are there existing workarounds or alternative solutions?
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"

  - type: textarea
    id: addtional
    attributes:
      label: Addtional Context
      description: Any other context.
    validations:
      required: false