name: Issue:Feature
description: New feature or change in sqeleton
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what feature is.
    validations:
      required: True
  

  - type: textarea
    id: todo
    attributes:
      label: To Do
      description: describe to do
    validations:
      required: False

  - type: dropdown
    id: attribution
    attributes:
      label: Attribution
      description: What kinds of feature?
      multiple: True
      options:
        - Migration from prototype to sqeleton
        - New feature
        - Documentation

  - type: textarea
    id: addtional
    attributes:
      label: Addtional Context
      description: Any other context.
    validations:
      required: False