name: Document Deploy

run-name: Document Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync --all-extras --frozen

      - name: Build docs
        run: |
          uv run make -C docs html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          publish_dir: ./docs/build/html

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v5