name: Yamllint

run-name: Yamllint

on:
  push:
    paths:
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/workflows/*.yml"
  workflow_dispatch:

jobs:
  Yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Running yamllint
        run: |
          yamllint .github/ISSUE_TEMPLATE
          yamllint .github/workflows
